export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";

export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOAD_TRANSACTIONS_SUCCESS = "LOAD_TRANSACTIONS_SUCCESS";
export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const LOAD_PROFILE_SUCCESS = "LOAD_PROFILE_SUCCESS";
export const LOAD_WATCHLIST_SUCCESS = "LOAD_WATCHLIST_SUCCESS";
export const LOAD_WALLET_SUCCESS = "LOAD_WALLET_SUCCESS";
export const LOAD_PRICE_SUCCESS = "LOAD_PRICE_SUCCESS";
export const LOAD_PRICE_HISTORICAL_SUCCESS = "LOAD_PRICE_HISTORICAL_SUCCESS";
export const LOAD_WATCHBAR_SUCCESS = "LOAD_WATCHBAR_SUCCESS";
export const LOAD_WALLET_CHART_SUCCESS = "LOAD_WALLET_CHART_SUCCESS";

export const DELETE_TRANSACTION_OPTIMISTIC = "DELETE_TRANSACTION_OPTIMISTIC";

export const RESET_PRICE_SUCCESS = "RESET_PRICE_SUCCESS";
export const RESET_PRICE_HISTORICAL_SUCCESS = "RESET_PRICE_HISTORICAL_SUCCESS";
// export const DELETE_PROFILE_WATCHLIST_OPTIMISTIC =
//   "DELETE_PROFILE_WATCHLIST_OPTIMISTIC";
